apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-rating
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-rating
  template:
    metadata:
      labels:
        app: movie-rating
    spec:
      containers:
        - name: movie-rating
          image: docker.io/library/app:v1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: "mongodb-service"
            - name: MONGO_PORT
              value: "27017"