apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-rating
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # At most 1 pod can be unavailable
      maxSurge: 1 # At most 1 extra pod during update
  selector:
    matchLabels:
      app: movie-rating
  template:
    metadata:
      labels:
        app: movie-rating
    spec:
      containers:
        - name: movie-rating
          image: docker.io/arthurvb/movie-rating:v1.0.9 # {"$imagepolicy": "flux-system:movie-rating-policy"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
