apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
  namespace: test
type: Opaque
stringData:
  password: "admin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-app-password
  namespace: test
type: Opaque
stringData:
  password: "app123"