apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:6.0.5
        command:
          - mongos
          - --configdb
          - mongodb-config/mongodb-config-0.mongodb-config-svc.mongodb.svc.cluster.local:27017,mongodb-config-1.mongodb-config-svc.mongodb.svc.cluster.local:27017,mongodb-config-2.mongodb-config-svc.mongodb.svc.cluster.local:27017
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: mongos-service
  namespace: test
spec:
  selector:
    app: mongos
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP