apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-operator
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: mongodb-kubernetes-operator
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - configmaps
    - secrets
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - apps
    resources:
    - statefulsets
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - mongodbcommunity.mongodb.com
    resources:
    - mongodbcommunity
    - mongodbcommunity/status
    - mongodbcommunity/spec
    - mongodbcommunity/finalizers
    verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-kubernetes-operator
rules:
  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - use
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-kubernetes-operator
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-kubernetes-operator
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-operator
    namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-kubernetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-kubernetes-operator
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      serviceAccountName: mongodb-kubernetes-operator
      containers:
      - name: mongodb-kubernetes-operator
        image: quay.io/mongodb/mongodb-kubernetes-operator:0.8.3
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "mongodb-kubernetes-operator"
        - name: MANAGED_SECURITY_CONTEXT
          value: "true"
        - name: AGENT_IMAGE
          value: "quay.io/mongodb/mongodb-agent-ubi:108.0.6.8796-1"
        - name: VERSION_UPGRADE_HOOK_IMAGE
          value: "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.8"
        - name: READINESS_PROBE_IMAGE
          value: "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.17"
        - name: MONGODB_IMAGE
          value: "mongo"
        - name: MONGODB_REPO_URL
          value: "docker.io"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8081
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /readyz
        #     port: 8081
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-database
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps","pods"]
    verbs: ["get", "list", "create", "update", "delete", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/status"] 
    verbs: ["get", "list", "create", "update", "delete", "watch", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "create", "update", "delete", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-database
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-database
subjects:
- kind: ServiceAccount
  name: mongodb-database
  namespace: test