apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-credentials
  namespace: test
type: Opaque
stringData:
  username: "${MONGODB_ADMIN_USERNAME}"
  password: "${MONGODB_ADMIN_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-user-credentials
  namespace: test
type: Opaque
stringData:
  username: "${MONGODB_APP_USERNAME}"
  password: "${MONGODB_APP_PASSWORD}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: test
data:
  MONGODB_TEST_DATABASE: "${MONGODB_TEST_DATABASE}"
  MONGODB_PROD_DATABASE: "${MONGODB_PROD_DATABASE}"
  MONGODB_DATABASE: "${MONGODB_TEST_DATABASE}"
  MONGODB_HOST: "mongos-service.test.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_OPTIONS: "authSource=admin&readPreference=primary"