apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: movie-rating-automation-production
  namespace: default
spec:
  suspend: false
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: production
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore: update movie-rating image [skip cd]
        
        Automation name: {{ .AutomationObject }}
    push:
      branch: production  # Push to same branch but with [skip cd]
  update:
    path: ./kubernetes/app-production
    strategy: Setters