apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: movie-rating-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: movie-rating-repository
  policy:
    semver:
      range: ">=1.0.0"
