apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP  # Changed from NodePort to ClusterIP for internal access only