apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-rating
  namespace: default
  annotations:
    # Tell Flux to update this image automatically
    fluxcd.io/set-image: "movie-rating=arthurvb/movie-rating:latest"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-rating
  template:
    metadata:
      labels:
        app: movie-rating
    spec:
      containers:
        - name: movie-rating
          image: arthurvb/movie-rating:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
