apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: movie-rating-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: movie-rating
  policy:
    alphabetical:
      order: asc  # `latest` will be picked automatically
