apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: movie-rating-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: movie-rating
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^[a-f0-9]{7}$'  # Only match 7-character SHA tags, ignore "latest"