name: Python Tests CI

on:
  push:
    branches: [ "dev-main" ]
  pull_request:
    branches: [ "dev-main" ]
  workflow_dispatch:

jobs:
  test-and-commit:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim
      options: --workdir /github/workspace/kubernetes-project


    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed for committing back

      # Install system dependencies inside the container
      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      # Run unit tests inside Docker
      - name: Run unit tests in Docker
        run: |
          PYTHONPATH=. pytest


      # Commit changes if tests pass (runs on host, not inside container)
      - name: Commit changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit after successful tests" || echo "No changes to commit"
          git push origin dev-main
