name: Python Tests CI

on:
  push:
    branches: [ "dev-main" ]
  pull_request:
    branches: [ "dev-main" ]
  workflow_dispatch:

jobs:
  test-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run unit tests inside Docker
      - name: Run unit tests in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: python:3.13-slim
          options: -v ${{ github.workspace }}:/github/workspace --workdir /github/workspace/kubernetes-project
          run: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install pytest
            PYTHONPATH=. pytest -v tests

      # Commit changes on host runner (Git is available)
      - name: Commit changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit after successful tests" || echo "No changes to commit"
          git push origin dev-main
