name: Python Tests CI

on:
  push:
    branches: [ "dev-main" ]
  pull_request:
    branches: [ "dev-main" ]
  workflow_dispatch:

jobs:
  test-and-commit:
    runs-on: ubuntu-latest
    container: python:3.13-slim  # All steps run in Docker

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed for committing back

      # Install system dependencies (Git, etc.)
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      # Run unit tests
      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest  # ensures 'app' is importable

      # Commit changes if tests pass
      - name: Commit changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit after successful tests" || echo "No changes to commit"
          git push origin dev-main
