name: Python Tests CI

on:
  push:
    branches: [ "dev-main" ]
  pull_request:
    branches: [ "dev-main" ]
  workflow_dispatch:

jobs:
  test-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed for committing back

      # Run tests inside Docker container
      - name: Run unit tests in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: python:3.13-slim
          options: -v ${{ github.workspace }}:/github/workspace
          run: |
            apt-get update
            apt-get install -y python3-pip
            pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install pytest
            PYTHONPATH=/github/workspace pytest

      # Commit changes if tests pass (outside container)
      - name: Commit changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit after successful tests" || echo "No changes to commit"
          git push origin dev-main
